### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Kaile-Du** [cdjkim/PRS#1]
The dataset_maker.py can not generate baseFormat.format(split=self.split, task_idx=task_idx, data='multi_hot_categories', dataset=data_name, ext='json'

**Comment by ecrireme** [comment]
Hi, Thank you for having an interest in PRS.
The code was generating the `multi_hot_categories.json` file, but there seems to have been a typo in the filename.
Instead of saving as `multi_hot_categories.json`, `label.json` was saved.
We have fixed the bug, and several data file names have been updated.
You can now generate `{split}_{taskid}_multi_hot_categories_{dataset}.json` files from the fixed code.
Sorry for the inconvenience.

**Comment by valencebond** [comment]
> The dataset_maker.py can not generate baseFormat.format(split=self.split, task_idx=task_idx, data='multi_hot_categories', dataset=data_name, ext='json'

can you success reimplement the performance reported by the paper?

**Comment by cdjkim** [comment]
Hi, regarding the performance reproducibility follow [here](https://github.com/cdjkim/PRS/issues/15)!
